### ISSUE TITLE
Need to better name/organize your reports

### ISSUE THREAD

**Issue by ugurdogrusoz** [yitepeli/CS319Project_Group2D_LOST#8]
You have copies of reports all over the place. Please rename/reorganize your reports.

**Comment by gunduzhuseyn** [comment]
Hi,
Since, I could not figure out how to rename directories, in the github. I created new directories called Drafts and Submissions and copied files accordingly. However, the time stamp of the files changed. So is it ok if I remove the old files from the repository. Or is there a better way to rename directories and move files.

**Comment by ugurdogrusoz** [comment]
Now that I confirmed submission dates, you're free to do whatever. Besides, old files are not lost, and can be reached anyway.

**Comment by gunduzhuseyn** [comment]
Ok,
I cleaned up the place.
